name: CI/CD for Bliss Mart Ecommerce

on: 
  push:
     branches:
           - main

  workflow_dispatch:

permissions:
     contents: write

jobs:
   build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      
          
      - name: Install dependencies
        run: npm run install

      - name: Build Tailwind CSS
        run: tailwindcss -i ./src/index.css -o ./src/output.css --watch

      - name: Build Project
        run: npm run build
      
      - name: Deploy on Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist
